apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: petclinic3
  namespace: openshift-gitops
spec:
  destination:
    namespace: petclinic3
    server: https://kubernetes.default.svc
  project: default
  source:
    helm:
      valueFiles:
      - values.yaml
    path:  helm/pet-clinic/
    repoURL: https://github.com/CSA-RH/helm-gitops-sscsi_secrets.git
    targetRevision: HEAD
