apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: azure-kvname
spec:
  provider: azure
  secretObjects:
  - data:
    - objectName: {{ .Values.secretprovider.objectName }}
      key: username
    secretName: {{ .Values.secretprovider.secretName }}
    type: Opaque
  parameters:
    usePodIdentity: "false"
    useVMManagedIdentity: "false"
    keyvaultName: {{ .Values.secretprovider.keyvaultName }} # the name of the KeyVault
    tenantId: {{ .Values.secretprovider.tenantId }}                               # the tenant ID of the KeyVault  
    objects:  |
      array:
        - |
          objectName: {{ .Values.secretprovider.objectName }}
          objectType: secret