apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: aws-kvname
spec:
  provider: aws
  secretObjects:
  - data:
    - objectName: db_password
      key: password
    secretName: {{ .Values.secretprovider.secretName }}
    type: Opaque
  parameters:
    objects: |
        - objectName: "{{ .Values.secretprovider.objectName }}"    
          objectType: "secretsmanager"
          jmesPath:
            - path: password
              objectAlias: db_password

##key: password: aws-secrets-manager_secretKey
##objectName: secret-name-from-secrets-manager
##secretName: secret-name-to-create-in-k8s-cluster


#apiVersion: secrets-store.csi.x-k8s.io/v1
#kind: SecretProviderClass
#metadata:
#  name: aws-kvname
#spec:
#  provider: aws
#  parameters:
#    objects: |
#        - objectName: "{{ .Values.secretprovider.objectName }}"    
#          objectType: "secretsmanager"
#  secretObjects:
#  - data:
#    - objectName: {{ .Values.secretprovider.objectName }}
#      key: password
#    secretName: {{ .Values.secretprovider.secretName }}
#    type: Opaque
##key: password: aws-secrets-manager_secretKey
##objectName: secret-name-from-secrets-manager
##secretName: secret-name-to-create-in-k8s-cluster