apiVersion: v1
kind: ServiceAccount
metadata:
  annotations:
    {{- toYaml .Values.serviceaccount.annotations | nindent 4 }}
  creationTimestamp: null
  name: {{ .Values.serviceaccount.name }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  creationTimestamp: null
  name: system:openshift:scc:mysqlscc
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: system:openshift:scc:mysqlscc
subjects:
- kind: ServiceAccount
  name: {{ .Values.serviceaccount.name }}
  namespace:  {{ .Values.crb.namespace }}

