petclinic:
  app: spring-petclinic
  name: spring-petclinic
  image: quay.io/rdiazgav/spring-petclinic:latest
service:
  app: spring-petclinic
  name: spring-petclinic
  type: ClusterIP
secretprovider:
  secretName: demosecret4        # K8s secret object that should be created 
  objectName: MySecret7          # Name of the secret created in AWS Secret Manager Vault
crb:
  namespace: petclinic3
serviceaccount:
  annotations:
    #changeme:
    eks.amazonaws.com/role-arn: arn:aws:iam::435036459222:role/openshift-access-to-mysecret7
  name: mysa3

    #lmartin222d
    #arn:aws:iam::295090537092:role/openshift-access-to-mysecret7
    #lmartin222c
    #eks.amazonaws.com/role-arn: arn:aws:iam::435036459222:role/openshift-access-to-mysecret7
