apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: system:openshift:scc:mysqlscc
rules:
- apiGroups:
  - security.openshift.io
  resourceNames:
  - mysqlscc
  resources:
  - securitycontextconstraints
  verbs:
  - use